# -*- coding: utf-8 -*-
"""emotion-finetune-lora.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aVYIghyxXBYvMbwcsMvEkfMcLhFdfVut
"""

import os

folders = [
    "emotion-finetune-lora/data",
    "emotion-finetune-lora/src",
    "emotion-finetune-lora/notebooks"
]

for folder in folders:
    os.makedirs(folder, exist_ok=True)

# create empty files
files = [
    "emotion-finetune-lora/src/dataset.py",
    "emotion-finetune-lora/src/model.py",
    "emotion-finetune-lora/src/train.py",
    "emotion-finetune-lora/src/evaluate.py",
    "emotion-finetune-lora/requirements.txt",
    "emotion-finetune-lora/README.md",
    "emotion-finetune-lora/.gitignore"
]

for file in files:
    open(file, "w").close()

print("Done!")

!pip install torchao --upgrade -q

import pandas as pd

df = pd.read_csv("/content/emotion-finetune-lora/data/ISEAR.csv")
df = df[["content", "sentiment"]].dropna()
df = df.rename(columns={"content": "text", "sentiment": "label"})
print("Done:", len(df))

from datasets import Dataset
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from transformers import AutoTokenizer, TrainingArguments, Trainer, DataCollatorWithPadding, AutoModelForSequenceClassification
from peft import get_peft_model, LoraConfig, TaskType

le = LabelEncoder()
df["label"] = le.fit_transform(df["label"])

print("Classes:", le.classes_)
print("Dataset size:", len(df))

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42, stratify=df["label"])
train_data = Dataset.from_pandas(train_df.reset_index(drop=True))
test_data = Dataset.from_pandas(test_df.reset_index(drop=True))

# --- TOKENIZE ---
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")

def tokenize(batch):
    return tokenizer(batch["text"], padding="max_length", truncation=True, max_length=128)

train_data = train_data.map(tokenize, batched=True)
test_data = test_data.map(tokenize, batched=True)

# --- MODEL ---
base_model = AutoModelForSequenceClassification.from_pretrained(
    "distilbert-base-uncased", num_labels=len(le.classes_)
)
lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r=8, lora_alpha=16, lora_dropout=0.1,
    target_modules=["q_lin", "v_lin"]
)
model = get_peft_model(base_model, lora_config)
model.print_trainable_parameters()

training_args = TrainingArguments(
    output_dir="/content/emotion-finetune-lora/model_output",
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    eval_strategy="epoch",
    save_strategy="epoch",
    logging_steps=50,
    load_best_model_at_end=True,
    report_to="none"
)
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_data,
    eval_dataset=test_data,
    processing_class=tokenizer,
    data_collator=DataCollatorWithPadding(tokenizer)
)

trainer.train()
print("Done! Classes:", le.classes_)

from sklearn.metrics import classification_report
import numpy as np

predictions = trainer.predict(test_data)
preds = np.argmax(predictions.predictions, axis=-1)
labels = predictions.label_ids

print(classification_report(labels, preds, target_names=le.classes_))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/emotion-finetune-lora/README.md
# # Emotion Classification with LoRA Fine-tuning
# 
# Fine-tuned DistilBERT on emotion dataset using LoRA adapters (PEFT).
# Classifies text into 4 emotions: anger, fear, joy, sadness.
# 
# ## Why LoRA
# Full fine-tuning updates 67M parameters. LoRA trains only 741K (1.09%)
# by adding small adapter matrices — same result, fraction of the compute.
# 
# ## Results
# | Class   | F1   |
# |---------|------|
# | Anger   | 0.76 |
# | Fear    | 0.75 |
# | Joy     | 0.78 |
# | Sadness | 0.69 |
# | **Weighted Avg** | **0.75** |
# 
# ## How to Run
# pip install -r requirements.txt
# python src/train.py
# python src/evaluate.py
# 
# ## Connection to Research
# Modern version of the BiLSTM emotion classifier from my IEEE paper
# (F1 = 0.7595). DistilBERT + LoRA achieves comparable F1 with
# transformer architecture and only 1% trainable parameters.

import subprocess

commands = [
    "cd /content/emotion-finetune-lora && git init",
    "cd /content/emotion-finetune-lora && git add README.md src/",
    'cd /content/emotion-finetune-lora && git commit -m "add LoRA training pipeline and results: F1=0.75"',
    "cd /content/emotion-finetune-lora && git branch -M main",
    "cd /content/emotion-finetune-lora && git remote add origin https://github.com/bhavnish04/emotion-finetune-lora.git",
    "cd /content/emotion-finetune-lora && git push -u origin main"
]

for cmd in commands:
    print(subprocess.getoutput(cmd))

!git config --global user.email "bhavnish0402@gmail.com"
!git config --global user.name "Bhavnish Singhall"

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# cd /content/emotion-finetune-lora
# git add README.md src/
# git commit -m "add LoRA training pipeline and results: F1=0.75"

